# address: 'smtp.yourserver.com'
# port: '25'
# user_name: 'user'
# password: 'password'
# authentication: :plain # :plain, :login, :cram_md5, no auth by default
# domain: "localhost.localdomain" # the HELO domain provided by the client to the server

location: /usr/sbin/sendmail
arguments: '-t -i'
